### ISSUE TITLE
GLOVE embedings

### ISSUE THREAD

**Issue by states786** [4OH4/doc-similarity#1]
Hi, 

As you mentioned in the post "By default, a GloVe word embedding model is loaded (glove-wiki-gigaword-50), although a custom model can also be used."

Will the following command fine tune GLOVE embedding on my own dataset or what is the way to fine-tune embeddings on my own dataset?

```
from docsim import DocSim

docsim = DocSim(verbose=True)

similarities = docsim.similarity_query(query_string, documents)
```

Finally, I have around 500 queries, for which I would like to retrieve similar documents from the corpus containing 15K documents. For this purpose, I am using following command:

`similarities = docsim.similarity_query(query_string, documents) `

But, it is extremely slow. Is there any possibility to speedup?

**Comment by 4OH4** [comment]
Hello there,
All the code in the repository is based around pre-trained models, there is not functionality there to fine tune or otherwise retrain the embeddings model. So... you could train your own model elsewhere and use it with the DocSim class, and pass the model object to the constructor:

    docsim = DocSim(model=myTrainedModel)

There a number of blogs on retraining GloVe embeddings visible on Google search, although looks like it is quite memory hungry so may require some substantial resource.

As for the execution time, the word embedding models are quite slow generally, as they are large files. The slowest part is loading the model: on my machine it takes about 40 seconds, so the first thing is to make sure that the model is only being loaded once (that is the reason for wrapping it up inside an object - DocSim). Other than that, I don't know any tricks to make it run faster. Running multiple queries in parallel would help, of course. 

I don't believe GenSim currently runs on the GPU for this kind of task - there is an open issue looking at word2ved: https://github.com/RaRe-Technologies/gensim/issues/449

Do let us know if you find out anything relevant.

**Comment by states786** [comment]
Thanks for your guidance
