### ISSUE TITLE
About fair comparison

### ISSUE THREAD

**Issue by states786** [4OH4/doc-similarity#2]
Hi,

In the doc-similarity library, there are two implementations TF-IDF and GLOVE. However,regular cosine similarity is calculated for TF-IDF, where as in GLOVE soft-cosine similarity is measured.

Due to the difference in similarity metric, can it be possible to achieve fair comparison in results between TF-IDF and GLOVE?

**Comment by 4OH4** [comment]
Hi there, yes - that's a good point. The two approaches are looking at the problem from two different approaches. 

TF-idf is looking at the term overlap, i.e. the number of shared words between the two documents in question (and also how important/significant those words are in the documents). 

The GloVe embedding is looking at how similar the words are (how frequently pairs of words appear near each other in general usage), so the soft cosine similarity should be used (rather than regular cos similarity).

So, I would suggest that the scores from the two different metrics should not be directly compared. 

Instead, view the results in the context of a particular application - how well do the different approaches measure the separation between documents that are known to be on different topics, vs how well do they cluster documents that are known to be similar.

**Comment by states786** [comment]
Thanks for your guidance....
