### ISSUE TITLE
Any fast way to retrieve similar documents through GLOVE

### ISSUE THREAD

**Issue by states786** [4OH4/doc-similarity#4]
Hi,

I have 100 queries and I have to extract similar set of 10 documents from a corpus of 15K documents by using GLOVE. So, when I use the following code snippet it will take lot of time to achieve results for each query.

`docsim_obj.similarity_query(query, corpus)`

In this experiment, corpus is the same for all the queries. So, can it be possible to achieve the results in a fast way? If yes, what type of changes do I require in the code?

**Comment by 4OH4** [comment]
In the example notebook I ran a few timing tests to show which parts of the process took the longest to run - you'll see a few cells that are followed by 'Wall time: 7.73 s'. That might be useful indicator of which parts of the process would be most important to speed up.

Obviously, you only want to load the model once, as that is the longest part (32 seconds) - hence why we have the DocSim object stored in memory.

Constructing the term dictionary and similarity matrix was also slow - 7.7 seconds. We can make this faster by re-using our term dictionary and matrix, **IF** we can make an assumption about the words in the query string and the corpus...

If you look in the code for `DocSim.similarity_query()`, you'll see that we construct a new term dictionary and matrix for each query - this is because we combine the query string with the corpus to be sure that the words we are comparing are referenced. If the corpus is big enough, its fair to assume that the words you are querying already exist in the corpus, so there is no need to add them. Hence, you can just create the term dictionary and similarity matrix once, and re-use it for each query.

Computing the SoftCosineSimilarity is pretty fast, I think. If you wanted that to go faster, perhaps parallelisation may help.
